[build]
command = "yarn && yarn storybook:build"

[build.environment]
YARN_VERSION = "1.22.19"
NODE_VERSION = "18.12.1"
CXXFLAGS = "-I/home/linuxbrew/.linuxbrew/include"
LDFLAGS = "-L/home/linuxbrew/.linuxbrew/lib"
