env:
  ARTIFACT_BUCKET: s3://ci-output-sink
steps:

  - input: ':recycle: Trigger ‘x86_64-darwin’'
    key: 'trigger-x86_64-darwin'

  - input: ':recycle: Trigger ‘aarch64-darwin’'
    key: 'trigger-aarch64-darwin'

  - label: 'daedalus-x86_64-darwin'
    command: 'scripts/with-nix-2.5.sh scripts/build-installer-unix.sh --build-id $BUILDKITE_BUILD_NUMBER'
    depends_on: 'trigger-x86_64-darwin'
    agents:
      queue: daedalus
      system: x86_64-darwin

  - label: 'daedalus-aarch64-darwin'
    command: 'scripts/with-nix-2.5.sh scripts/build-installer-unix.sh --build-id $BUILDKITE_BUILD_NUMBER'
    depends_on: 'trigger-aarch64-darwin'
    env:
      UPLOAD_DIR_OVERRIDE: UNSAFE-internal-build
    agents:
      queue: daedalus
      system: aarch64-darwin

  - label: 'daedalus-x86_64-linux-nix'
    command: 'scripts/with-nix-2.5.sh scripts/build-installer-nix.sh $BUILDKITE_BUILD_NUMBER'
    agents:
      system: x86_64-linux

  - label: 'daedalus-x86_64-windows-nix'
    command: 'scripts/with-nix-2.5.sh scripts/build-cross-windows.sh $BUILDKITE_BUILD_NUMBER'
    agents:
      system: x86_64-linux

  # TODO: Re-enable once script is fixed
  # - label: 'release.nix'
  #   command: 'ci/check-hydra.sh'
  #   agents:
  #     system: x86_64-linux
