name: Verify Pull Request
on:
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Restore node_modules from cache
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install native dependencies
        run: sudo apt-get install libudev-dev
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run checks
        run: yarn check:all
      - name: Ensure there are no uncommited changes
        run: git diff --exit-code || (echo "Did you forget to run 'yarn check:all' and commit changes?" && exit 1)
      - name: Run tests
        run: yarn test:jest --maxWorkers=3
